apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myargo
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
    # matchExpressions:
    #   - {key : app, operator: In, values: [wordpress]}
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:5.8.3-php7.4-apache
        name: wordpress
        # env:
        #   - name: WORDPRESS_DB_HOST
        #     value: word-sql-db

        #   - name: WORDPRESS_DB_PASSWORD
        #     valueFrom:
        #       secretKeyRef:
        #         name: mysqlsecret
        #         key: root_pass
        ports:
          - containerPort: 80
            name: wordpress
            
        volumeMounts:
          - name: wordpress-data
            mountPath: /var/www

      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-volume