# claim 2GiB 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: helm-argo-cd
  name: wp-pvc1
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi