# connect wordpress to outside world

apiVersion: v1
kind: Service
metadata:
  namespace: myargo
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
