# connect wordpress to outside world

apiVersion: v1
kind: Service
metadata:
  namespace: myargo
  name: wordpress
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: wordpress
  type: LoadBalancer
